### ISSUE TITLE
生产环境部署

### ISSUE THREAD

**Issue by threetown** [master-nan/vue-thinkphp-admin#1]
master-nan，你好。我看到你项目
* 前端访问地址是：http://demo.walnutech.com，并使用 `history` 模式；
* 后台访问地址是：http://api.walnutech.com

想请教一下，生产环境部署的时候，是用怎么部署的，部署的配置文件可以分享一下吗？谢谢哈！

**Comment by master-nan** [comment]
额。。。前端是用nginx部署的，php用的apache
我的nginx配置客户端配置：

> server {
    # 端口
    listen 80;
    # 访问名
    server_name demo.walnutech.com;
    # 站点根目录
    root  /home/git/vue-thinkphp-admin/client/dist;
    set $root /home/git/vue-thinkphp-admin/client/dist;
    # 访问日志
    access_log logs/vue-thinkphp-admin.access.log;
    # 默认请求
    location / {
       # root /home/git/vue-thinkphp-admin/client/dist;
       # index index.html index.htm;
       # if ( -f $request_filename) {
       #     break;
       # }
       try_files $uri $uri/ /index.html;
    }
    # 静态文件
    location ~ ^/(images|javascript|js|css|flash|media|static)/ {
        expires 10d;
        root $root;
    }
    # 禁止访问 .htxxx 文件
    location ~ /.ht {
        deny all;
    }
    gzip on;
    gzip_buffers 32 4k;
    gzip_comp_level 6;
    gzip_min_length 200;
    gzip_types text/css text/xml application/javascript;
    gzip_vary on;
}

因为服务端是apache部署了，为了能用80端口，在nginx加入配置指向php部署的端口

> server {
    # 端口
    listen 80;
    # 访问名
    server_name api.walnutech.com;
    # 访问日志
    access_log logs/vue-thinkphp-admin-server.access.log;
    # 默认请求
    location / {
       proxy_pass              http://127.0.0.1:9090;
       proxy_redirect          off;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    # 静态文件
    location ~ ^/(images|javascript|js|css|flash|media|static)/ {
        expires 10d;
        root $root;
    }
    # 禁止访问 .htxxx 文件
    location ~ /.ht {
        deny all;
    }
    gzip on;
    gzip_buffers 32 4k;
    gzip_comp_level 6;
    gzip_min_length 200;
    gzip_types text/css text/xml application/javascript;
    gzip_vary on;
}

至于php部分得先启动fpm服务 并且apache监听fpm 9000 端口，默认是9000
`<FilesMatch \.php$>
    SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>`


至于apache的配置你上网搜下吧。。。我就不贴那么多了。。。部署完以后记得给目录读写权限
